/* Oasis Cashflow Sync — CRM/Facturación Style */
const HUB_URL = "https://eliezelapolinaris2017-lab.github.io/oasis-hub/";
const KEY = "oasis_cashflow_pro_v2_crm_sync";
const OLD_KEY = "oasis_cashflow_pro_v1";
const OWNER_EMAIL = "nexustoolspr@gmail.com";
const FIREBASE_APP_NAME = "oasis-suite-cashflow-live";
const firebaseConfig = { apiKey:"AIzaSyBm67RjL0QzMRLfo6zUYCI0bak1eGJAR-U", authDomain:"oasis-facturacion.firebaseapp.com", projectId:"oasis-facturacion", storageBucket:"oasis-facturacion.firebasestorage.app", messagingSenderId:"84422038905", appId:"1:84422038905:web:b0eef65217d2bfc3298ba8" };
let fbApp=null, fbAuth=null, fbDb=null, fbUser=null, unsub=null, activeTxId=null, liveReady=false, pushTimer=null, applyingRemote=false, calcValue="";
const $=id=>document.getElementById(id); const fmt=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(n||0)); const today=()=>new Date().toISOString().slice(0,10); const uid=(p="id")=>`${p}_${Date.now()}_${Math.random().toString(16).slice(2)}`; const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const emptyDB=()=>({cats:[],tx:[],recurring:[],meta:{lastBackupAt:"",lastRecurringRun:"",liveSync:true}});
function loadDB(){ let raw=localStorage.getItem(KEY); if(!raw && localStorage.getItem(OLD_KEY)){ localStorage.setItem(KEY, localStorage.getItem(OLD_KEY)); raw=localStorage.getItem(KEY); } try{return JSON.parse(raw||JSON.stringify(emptyDB()));}catch{return emptyDB();}}
function saveDB(db,{push=true}={}){ localStorage.setItem(KEY,JSON.stringify(db)); renderAll(); if(push && !applyingRemote) schedulePush(); }
function inRange(iso,from,to){ if(!iso)return false; if(from&&iso<from)return false; if(to&&iso>to)return false; return true; }
function setSync(text,state="local"){ $("syncPill").textContent=text; const dot=$("syncDot"); dot.className="syncDot"+(state==="on"?" on":state==="busy"?" busy":""); }
function assertOwner(u){ if(!u)throw new Error("No hay sesión."); if(String(u.email||"").toLowerCase()!==OWNER_EMAIL) throw new Error("Cuenta no autorizada."); }
function initFirebase(){ try{ if(!window.firebase)return; try{fbApp=firebase.app(FIREBASE_APP_NAME);}catch{fbApp=firebase.initializeApp(firebaseConfig,FIREBASE_APP_NAME)} fbAuth=firebase.auth(fbApp); fbDb=firebase.firestore(fbApp);}catch(e){console.warn(e)} }
function docRef(){ return fbDb.collection("users").doc(fbUser.uid).collection("apps").doc("cashflow"); }
function schedulePush(){ if(!fbUser||!fbDb||!liveReady)return; clearTimeout(pushTimer); setSync("Sincronizando…","busy"); pushTimer=setTimeout(pushNow,650); }
async function pushNow(){ if(!fbUser||!fbDb)return; try{ await docRef().set({updatedAt:new Date().toISOString(),ownerEmail:OWNER_EMAIL,db:loadDB()},{merge:true}); setSync("Sync al día","on"); }catch(e){ console.warn(e); setSync("Sync pendiente","local"); } }
function startLiveSync(){ if(unsub)unsub(); if(!fbUser||!fbDb)return; liveReady=true; unsub=docRef().onSnapshot(snap=>{ if(!snap.exists){pushNow();return;} const cloud=snap.data()?.db; if(!cloud)return; const local=loadDB(); const remoteTime=Date.parse(snap.data()?.updatedAt||0); const localTime=Date.parse(local.meta?.localUpdatedAt||0); if(remoteTime>=localTime){ applyingRemote=true; localStorage.setItem(KEY,JSON.stringify({cats:cloud.cats||[],tx:cloud.tx||[],recurring:cloud.recurring||[],meta:{...(local.meta||{}),...(cloud.meta||{}),cloudUpdatedAt:snap.data()?.updatedAt||""}})); applyingRemote=false; renderAll(); setSync("Sync vivo","on"); } }); }
async function loginGoogle(){ if(!fbAuth)return alert("Firebase no está listo."); try{ const res=await fbAuth.signInWithPopup(new firebase.auth.GoogleAuthProvider()); assertOwner(res.user); }catch(e){ alert(e.message||"Login cancelado."); try{await fbAuth.signOut()}catch{} } }
async function logout(){ if(unsub)unsub(); liveReady=false; try{await fbAuth.signOut()}catch{} }
function wireAuth(){ $("btnLogin").onclick=loginGoogle; $("btnLogout").onclick=logout; if(!fbAuth){setSync("Offline local","local");return;} fbAuth.onAuthStateChanged(async u=>{ if(!u){fbUser=null; $("authPill").textContent="Offline"; $("btnLogin").style.display=""; $("btnLogout").style.display="none"; setSync("Local activo","local"); return;} try{assertOwner(u); fbUser=u; $("authPill").textContent="Cloud conectado"; $("btnLogin").style.display="none"; $("btnLogout").style.display=""; startLiveSync(); setSync("Sync vivo","on");}catch(e){alert(e.message); await fbAuth.signOut();} }); }
function seedCats(){ const base=[ ["Servicios", "INCOME", "#38bdf8"],["Mantenimientos","INCOME","#22c55e"],["Instalaciones","INCOME","#d6b15a"],["Emergencias","INCOME","#2563eb"],["Materiales","EXPENSE","#f59e0b"],["Combustible","EXPENSE","#ef4444"],["Herramientas","EXPENSE","#d6b15a"],["Publicidad","EXPENSE","#38bdf8"],["Teléfono / Internet","EXPENSE","#8b5cf6"],["Misceláneos","BOTH","#94a3b8"] ]; const db=loadDB(); const seen=new Set(db.cats.map(c=>c.name.toLowerCase())); base.forEach(([name,type,color])=>{if(!seen.has(name.toLowerCase()))db.cats.push({id:uid("cat"),name,type,color,createdAt:new Date().toISOString()});}); db.meta.localUpdatedAt=new Date().toISOString(); saveDB(db); }
function addCat(){ const name=$("catName").value.trim(); if(!name)return alert("Nombre requerido."); const db=loadDB(); db.cats.push({id:uid("cat"),name,type:$("catType").value,color:$("catColor").value,createdAt:new Date().toISOString()}); db.meta.localUpdatedAt=new Date().toISOString(); $("catName").value=""; saveDB(db); }
function fillCats(){ const db=loadDB(); const cats=[...db.cats].sort((a,b)=>a.name.localeCompare(b.name)); const selects=["txCategory","txCategoryMirror","fCategory","rCategory"]; selects.forEach(id=>{ const el=$(id); if(!el)return; el.innerHTML=id==="fCategory"?'<option value="">Categoría</option>':''; cats.forEach(c=>{ const o=document.createElement("option"); o.value=c.id; o.textContent=c.name; el.appendChild(o); }); }); $("catBody").innerHTML=cats.map(c=>`<div class="compactItem"><span><b>${esc(c.name)}</b><br><small>${esc(c.type)}</small></span><button class="btn danger" data-del-cat="${esc(c.id)}">Borrar</button></div>`).join("")||'<p class="muted">Sin categorías.</p>'; document.querySelectorAll("[data-del-cat]").forEach(b=>b.onclick=()=>{const db=loadDB(); db.cats=db.cats.filter(c=>c.id!==b.dataset.delCat); db.meta.localUpdatedAt=new Date().toISOString(); saveDB(db);}); }
function currentType(){ return $("txType").value || "INCOME"; }
function syncMirrors(fromQuick=true){ const pairs=[["txAmount","txAmountMirror"],["txDate","txDateMirror"],["txCategory","txCategoryMirror"],["txMethod","txMethodMirror"],["txStatus","txStatusMirror"],["txParty","txPartyMirror"],["txRef","txRefMirror"],["txTags","txTagsMirror"],["txNotes","txNotesMirror"]]; pairs.forEach(([a,b])=>{if($(a)&&$(b)){ if(fromQuick) $(b).value=$(a).value; else $(a).value=$(b).value; }}); if(!fromQuick && $("txType")){ setType($("txType").value,false); } }
function setType(type, updateSelect=true){ if(updateSelect)$("txType").value=type; document.querySelectorAll(".segBtn").forEach(b=>b.classList.toggle("is-active",b.dataset.type===type)); }
function resetTx(){ activeTxId=null; $("txMode").textContent="Nuevo"; setType("INCOME"); ["txAmount","txParty","txRef","txTags","txNotes"].forEach(id=>$(id).value=""); $("txDate").value=today(); $("txMethod").value="EFECTIVO"; $("txStatus").value="PAGADO"; syncMirrors(true); showReceipt(null); }
function getReceipt(existing){ const file=$("txReceiptMirror").files?.[0] || $("txReceipt").files?.[0]; if(!file)return Promise.resolve(existing||null); return new Promise((res,rej)=>{const r=new FileReader(); r.onload=()=>res({name:file.name,type:file.type,sizeKB:Math.round(file.size/1024),dataUrl:String(r.result||"")}); r.onerror=rej; r.readAsDataURL(file);}); }
async function saveTx(fromMirror=false){ if(fromMirror)syncMirrors(false); else syncMirrors(true); const db=loadDB(); if(!db.cats.length){seedCats(); return alert("Creé la plantilla de categorías. Guarda nuevamente.");} const existing=db.tx.find(t=>t.id===activeTxId); const amount=Number($("txAmount").value||0); if(amount<=0)return alert("Monto inválido."); const item={id:activeTxId||uid("tx"),type:$("txType").value,date:$("txDate").value||today(),amount,categoryId:$("txCategory").value,method:$("txMethod").value,status:$("txStatus").value,party:$("txParty").value.trim(),ref:$("txRef").value.trim(),tags:$("txTags").value.trim(),notes:$("txNotes").value.trim(),receipt:await getReceipt(existing?.receipt),updatedAt:new Date().toISOString(),createdAt:existing?.createdAt||new Date().toISOString()}; const idx=db.tx.findIndex(t=>t.id===item.id); if(idx>=0)db.tx[idx]=item; else db.tx.unshift(item); db.meta.localUpdatedAt=new Date().toISOString(); activeTxId=item.id; $("txMode").textContent="Editando"; saveDB(db); alert("Guardado ✅ Sync activo."); }
function openTx(id){ const db=loadDB(); const t=db.tx.find(x=>x.id===id); if(!t)return; activeTxId=id; $("txMode").textContent="Editando"; setType(t.type||"INCOME"); $("txDate").value=t.date||today(); $("txAmount").value=t.amount||""; $("txCategory").value=t.categoryId||""; $("txMethod").value=t.method||"EFECTIVO"; $("txStatus").value=t.status||"PAGADO"; $("txParty").value=t.party||""; $("txRef").value=t.ref||""; $("txTags").value=t.tags||""; $("txNotes").value=t.notes||""; syncMirrors(true); showReceipt(t.receipt); setView("transactions"); }
function deleteTx(){ if(!activeTxId)return resetTx(); if(!confirm("¿Borrar movimiento?"))return; const db=loadDB(); db.tx=db.tx.filter(t=>t.id!==activeTxId); db.meta.localUpdatedAt=new Date().toISOString(); saveDB(db); resetTx(); }
function duplicateTx(){ if(!activeTxId)return alert("Abre un movimiento primero."); const db=loadDB(); const t=db.tx.find(x=>x.id===activeTxId); if(!t)return; const copy={...t,id:uid("tx"),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; db.tx.unshift(copy); db.meta.localUpdatedAt=new Date().toISOString(); saveDB(db); openTx(copy.id); }
function showReceipt(r){ $("receiptMeta").textContent=r?`${r.name} · ${r.sizeKB||0} KB`:"Sin recibo"; $("receiptImg").src=r?.dataUrl||""; $("receiptImg").style.display=r?.dataUrl?"block":"none"; }
function getCat(db,id){return db.cats.find(c=>c.id===id)||null}
function filteredTx(){ const db=loadDB(); const text=($("fText").value||"").toLowerCase(); return db.tx.filter(t=>{ if($("fType").value&&t.type!==$("fType").value)return false; if($("fStatus").value&&t.status!==$("fStatus").value)return false; if($("fCategory").value&&t.categoryId!==$("fCategory").value)return false; if($("fMethod").value&&t.method!==$("fMethod").value)return false; if(!inRange(t.date,$("fFrom").value,$("fTo").value))return false; if(text && ![t.party,t.ref,t.tags,t.notes].join(" ").toLowerCase().includes(text))return false; return true; }).sort((a,b)=>(b.date||"").localeCompare(a.date||"")); }
function renderTable(){ const db=loadDB(); const rows=filteredTx(); $("txBody").innerHTML=rows.map(t=>{ const c=getCat(db,t.categoryId); const inx=t.type==="INCOME"; return `<tr><td>${esc(t.date)}</td><td><span class="badge ${inx?'in':'out'}">${inx?'Ingreso':'Gasto'}</span></td><td>${esc(c?.name||'—')}</td><td>${esc(t.method)}</td><td>${esc(t.party||'—')}</td><td><span class="badge ${t.status==='PENDIENTE'?'pending':''}">${esc(t.status)}</span></td><td><b>${esc(fmt(t.amount))}</b></td><td><button class="btn ghost" data-open="${esc(t.id)}">Abrir</button></td></tr>`; }).join("")||'<tr><td colspan="8">Sin movimientos.</td></tr>'; document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openTx(b.dataset.open)); }
function totals(){ const db=loadDB(); const tx=db.tx.filter(t=>inRange(t.date,$("pFrom").value,$("pTo").value)); const income=tx.filter(t=>t.type==="INCOME").reduce((a,t)=>a+Number(t.amount||0),0); const expense=tx.filter(t=>t.type==="EXPENSE").reduce((a,t)=>a+Number(t.amount||0),0); return {db,tx,income,expense,net:income-expense}; }
function byCat(tx,type,db){ const m=new Map(); tx.filter(t=>t.type===type).forEach(t=>m.set(t.categoryId,(m.get(t.categoryId)||0)+Number(t.amount||0))); return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4).map(([id,v])=>`${esc(getCat(db,id)?.name||'—')}: <b>${esc(fmt(v))}</b>`).join('<br>')||'Sin data.'; }
function renderDash(){ const {db,tx,income,expense,net}=totals(); $("kpiIncome").textContent=fmt(income); $("kpiExpense").textContent=fmt(expense); $("kpiNet").textContent=fmt(net); const pending=tx.filter(t=>t.status==="PENDIENTE").reduce((a,t)=>a+Number(t.amount||0),0); $("dashGrid").innerHTML=`<div class="dashCard"><strong>Cashflow</strong><div class="meta">Ingresos <b>${fmt(income)}</b><br>Gastos <b>${fmt(expense)}</b><br>Balance <b>${fmt(net)}</b></div></div><div class="dashCard"><strong>${net>=0?'Operación saludable':'Margen bajo presión'}</strong><div class="meta">${net>=0?'La operación respira. Ahora escala con control.':'Hay fuga de dinero. No es drama, es tablero.'}</div></div><div class="dashCard"><strong>Pendiente</strong><div class="meta">Por cobrar/pagar: <b>${fmt(pending)}</b><br>Movimientos: <b>${tx.length}</b></div></div><div class="dashCard"><strong>Top ingresos</strong><div class="meta">${byCat(tx,'INCOME',db)}</div></div><div class="dashCard"><strong>Top gastos</strong><div class="meta">${byCat(tx,'EXPENSE',db)}</div></div><div class="dashCard"><strong>Sync / Backup</strong><div class="meta">Cloud: <b>${fbUser?'Activo':'Offline'}</b><br>Último backup: <b>${db.meta?.lastBackupAt?new Date(db.meta.lastBackupAt).toLocaleDateString():'Nunca'}</b></div></div>`; renderBackup(); }
function renderBackup(){ const db=loadDB(); const last=db.meta?.lastBackupAt; $("kpiBackupValue").textContent=last?"OK":"Pendiente"; $("kpiBackupSub").textContent=last?`Último ${new Date(last).toLocaleDateString()}`:"Toca para exportar"; }
function addRecurring(){ const db=loadDB(); const amount=Number($("rAmount").value||0); if(amount<=0)return alert("Monto inválido."); db.recurring.unshift({id:uid("rec"),type:$("rType").value,categoryId:$("rCategory").value,amount,day:Number($("rDay").value||1),party:$("rParty").value,memo:$("rMemo").value,createdAt:new Date().toISOString()}); db.meta.localUpdatedAt=new Date().toISOString(); saveDB(db); }
function renderRecurring(){ const db=loadDB(); $("recBody").innerHTML=db.recurring.map(r=>`<div class="compactItem"><span><b>${esc(getCat(db,r.categoryId)?.name||'—')}</b><br><small>${esc(r.type)} · día ${esc(r.day)} · ${esc(fmt(r.amount))}</small></span><button class="btn danger" data-del-rec="${esc(r.id)}">Borrar</button></div>`).join("")||'<p class="muted">Sin recurrentes.</p>'; document.querySelectorAll("[data-del-rec]").forEach(b=>b.onclick=()=>{const db=loadDB(); db.recurring=db.recurring.filter(r=>r.id!==b.dataset.delRec); db.meta.localUpdatedAt=new Date().toISOString(); saveDB(db);}); }
function runRecurring(){ const db=loadDB(); const d=new Date(), ym=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; if(db.meta.lastRecurringRun===ym&&!confirm("Ya corriste este mes. ¿Duplicar?"))return; db.recurring.forEach(r=>db.tx.unshift({id:uid("tx"),type:r.type,date:`${ym}-${String(r.day).padStart(2,'0')}`,amount:r.amount,categoryId:r.categoryId,method:"OTRO",status:"PENDIENTE",party:r.party,ref:"RECURRENTE",tags:"recurrente",notes:r.memo,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})); db.meta.lastRecurringRun=ym; db.meta.localUpdatedAt=new Date().toISOString(); saveDB(db); }
function exportJSON(){ const db=loadDB(); db.meta.lastBackupAt=new Date().toISOString(); localStorage.setItem(KEY,JSON.stringify(db)); const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),db},null,2)],{type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=`oasis_cashflow_backup_${today()}.json`; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),300); renderAll(); schedulePush(); }
async function importJSON(file){ try{ const data=JSON.parse(await file.text()); const db=data.db||data; if(!Array.isArray(db.tx)||!Array.isArray(db.cats))return alert("Archivo inválido."); db.meta={...(db.meta||{}),localUpdatedAt:new Date().toISOString()}; saveDB({cats:db.cats,tx:db.tx,recurring:db.recurring||[],meta:db.meta}); }catch{alert("No se pudo importar.");} }
function resetAll(){ if(!confirm("Reset total. ¿Seguro?"))return; saveDB(emptyDB()); }
function calcEval(){ try{ const exp=calcValue.replaceAll("÷","/").replaceAll("×","*").replace(/[^0-9.+\-*/()]/g,""); const val=Function(`"use strict";return (${exp||0})`)(); if(!Number.isFinite(val))throw 0; $("calcResult").textContent=`Resultado: ${fmt(val)}`; return Number(val.toFixed(2)); }catch{ $("calcResult").textContent="Resultado inválido"; return null; } }
function renderAll(){ fillCats(); renderTable(); renderDash(); renderRecurring(); }
function setView(name){ document.querySelectorAll(".view").forEach(v=>v.classList.toggle("is-active",v.id===`view-${name}`)); document.querySelectorAll(".navBtn").forEach(b=>b.classList.toggle("is-active",b.dataset.view===name)); }
function boot(){ $("hubBtn").href=HUB_URL; const now=new Date(), first=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10), last=new Date(now.getFullYear(),now.getMonth()+1,0).toISOString().slice(0,10); ["pFrom","fFrom"].forEach(id=>$(id).value=first); ["pTo","fTo"].forEach(id=>$(id).value=last); initFirebase(); wireAuth(); $("tabs").onclick=e=>{const b=e.target.closest(".navBtn"); if(b)setView(b.dataset.view);}; document.querySelectorAll(".segBtn").forEach(b=>b.onclick=()=>setType(b.dataset.type)); $("txType").onchange=()=>setType($("txType").value); ["btnSaveTx","btnSaveInline"].forEach(id=>$(id).onclick=()=>saveTx(false)); $("btnSaveMirror").onclick=()=>saveTx(true); $("btnQuickAdd").onclick=()=>{resetTx();setView("dashboard");}; $("btnDuplicate").onclick=duplicateTx; $("btnDeleteTx").onclick=deleteTx; ["txAmount","txDate","txCategory","txMethod","txStatus","txParty","txRef"].forEach(id=>$(id).addEventListener("input",()=>syncMirrors(true))); ["txAmountMirror","txDateMirror","txCategoryMirror","txMethodMirror","txStatusMirror","txPartyMirror","txRefMirror","txTagsMirror","txNotesMirror"].forEach(id=>$(id).addEventListener("input",()=>syncMirrors(false))); ["fText","fType","fStatus","fCategory","fMethod","fFrom","fTo"].forEach(id=>$(id).addEventListener("input",renderTable)); $("btnClearFilters").onclick=()=>{["fText","fType","fStatus","fCategory","fMethod"].forEach(id=>$(id).value=""); renderTable();}; ["pFrom","pTo"].forEach(id=>$(id).onchange=renderDash); $("btnSeedCats").onclick=seedCats; $("btnAddCat").onclick=addCat; $("btnClearCats").onclick=()=>{const db=loadDB(); db.cats=[]; db.meta.localUpdatedAt=new Date().toISOString(); saveDB(db);}; $("btnAddRecurring").onclick=addRecurring; $("btnRunRecurring").onclick=runRecurring; $("btnClearRecurring").onclick=()=>{const db=loadDB(); db.recurring=[]; db.meta.localUpdatedAt=new Date().toISOString(); saveDB(db);}; $("btnExport").onclick=exportJSON; $("kpiBackup").onclick=exportJSON; $("btnImport").onclick=()=>$("importFile").click(); $("importFile").onchange=e=>{const f=e.target.files?.[0]; if(f)importJSON(f); e.target.value="";}; $("btnReset").onclick=resetAll; $("calcKeys").onclick=e=>{if(e.target.tagName!=="BUTTON")return; const v=e.target.textContent; if(v==="C")calcValue=""; else calcValue+=v; $("calcDisplay").value=calcValue;}; $("calcDisplay").oninput=e=>calcValue=e.target.value; $("btnCalcEqual").onclick=calcEval; $("btnUseCalc").onclick=()=>{const v=calcEval(); if(v!==null){$("txAmount").value=v; syncMirrors(true);}}; if(!loadDB().cats.length)seedCats(); resetTx(); renderAll(); }
boot();
